/*M!999999\- enable the sandbox mode */ 

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;
/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+00:00' */;
/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*M!100616 SET @OLD_NOTE_VERBOSITY=@@NOTE_VERBOSITY, NOTE_VERBOSITY=0 */;

SET @OLD_AUTOCOMMIT=@@AUTOCOMMIT, @@AUTOCOMMIT=0;
LOCK TABLES `configurations` WRITE;
/*!40000 ALTER TABLE `configurations` DISABLE KEYS */;
INSERT INTO `configurations` (`id`, `name`, `platform`, `category`, `depends_on`, `script`, `run_as`, `type`) VALUES (1,'ssh-root-login','linux','misconfiguration','[\"ssh\"]','sed -i \'1s/^/PermitRootLogin yes\\n/\' /etc/ssh/sshd_config\nif command -v dnf &> /dev/null; then\n	systemctl restart sshd\nelse\n	systemctl restart ssh\nfi','root','bash');
INSERT INTO `configurations` (`id`, `name`, `platform`, `category`, `depends_on`, `script`, `run_as`, `type`) VALUES (2,'suid-find','linux','misconfiguration',NULL,'chmod +s $(which find)','root','bash');
INSERT INTO `configurations` (`id`, `name`, `platform`, `category`, `depends_on`, `script`, `run_as`, `type`) VALUES (3,'suid-nano','linux','misconfiguration','[{\"name\":\"install-package\",\"vars\":{\"PACKAGE\":\"nano\"}}]','chmod +s $(which nano)','root','bash');
INSERT INTO `configurations` (`id`, `name`, `platform`, `category`, `depends_on`, `script`, `run_as`, `type`) VALUES (4,'suid-vim','linux','misconfiguration','[{\"name\":\"install-package\",\"vars\":{\"PACKAGE\":\"vim\"}}]','chmod +s $(which vim)','root','bash');
INSERT INTO `configurations` (`id`, `name`, `platform`, `category`, `depends_on`, `script`, `run_as`, `type`) VALUES (5,'root-nginx','linux','misconfiguration','[\"nginx\"]','sed -E -i \"s/^[[:space:]]*user[[:space:]]+(nginx|www-data);/user root;/\" /etc/nginx/nginx.conf','root','bash');
INSERT INTO `configurations` (`id`, `name`, `platform`, `category`, `depends_on`, `script`, `run_as`, `type`) VALUES (7,'apache','linux','service',NULL,'#!/bin/bash\nset -e\nif command -v apt-get > /dev/null; then\n    DEBIAN_FRONTEND=noninteractive apt-get install -y apache2\n    systemctl enable apache2 && systemctl start apache2\nelif command -v dnf > /dev/null; then\n    dnf install -y httpd\n    systemctl enable httpd && systemctl start httpd\nelif command -v yum > /dev/null; then\n    yum install -y httpd\n    systemctl enable httpd && systemctl start httpd\nelse\n    echo \"[apache] No supported package manager found\" >&2; exit 1\nfi\necho \"[apache] Done\"\n','root','bash');
INSERT INTO `configurations` (`id`, `name`, `platform`, `category`, `depends_on`, `script`, `run_as`, `type`) VALUES (8,'bind','linux','service',NULL,'#!/bin/bash\nset -e\nif command -v apt-get > /dev/null; then\n    DEBIAN_FRONTEND=noninteractive apt-get install -y bind9 bind9utils bind9-doc\n    mkdir -p /etc/systemd/resolved.conf.d\n    printf \'[Resolve]\\nDNSStubListener=no\\n\' > /etc/systemd/resolved.conf.d/no-stub.conf\n    systemctl restart systemd-resolved 2>/dev/null || true\n    systemctl enable bind9 && systemctl start bind9\nelif command -v dnf > /dev/null; then\n    dnf install -y bind bind-utils\n    systemctl enable named && systemctl start named\nelif command -v yum > /dev/null; then\n    yum install -y bind bind-utils\n    systemctl enable named && systemctl start named\nelse\n    echo \"[bind] No supported package manager found\" >&2; exit 1\nfi\necho \"[bind] Done\"\n','root','bash');
INSERT INTO `configurations` (`id`, `name`, `platform`, `category`, `depends_on`, `script`, `run_as`, `type`) VALUES (9,'dovecot','linux','service',NULL,'#!/bin/bash\nset -e\nif command -v apt-get > /dev/null; then\n    DEBIAN_FRONTEND=noninteractive apt-get install -y dovecot-core dovecot-imapd dovecot-pop3d\nelif command -v dnf > /dev/null; then\n    dnf install -y dovecot\nelif command -v yum > /dev/null; then\n    yum install -y dovecot\nelse\n    echo \"[dovecot] No supported package manager found\" >&2; exit 1\nfi\nsystemctl enable dovecot && systemctl start dovecot\necho \"[dovecot] Done\"\n','root','bash');
INSERT INTO `configurations` (`id`, `name`, `platform`, `category`, `depends_on`, `script`, `run_as`, `type`) VALUES (10,'mysql','linux','service','[{\"name\":\"install-package\",\"vars\":{\"PACKAGE\":\"mariadb-server\"}},{\"name\":\"enable-service\",\"vars\":{\"SERVICE\":\"mariadb\"}}]','#!/bin/bash\necho \"[mysql] Installed via install-package, enabled via enable-service\"\n','root','bash');
INSERT INTO `configurations` (`id`, `name`, `platform`, `category`, `depends_on`, `script`, `run_as`, `type`) VALUES (11,'nginx','linux','service',NULL,'#!/bin/bash\nset -e\nif command -v apt-get > /dev/null; then\n    DEBIAN_FRONTEND=noninteractive apt-get install -y nginx\nelif command -v dnf > /dev/null; then\n    dnf install -y nginx\nelif command -v yum > /dev/null; then\n    yum install -y epel-release\n    yum install -y nginx\nelse\n    echo \"[nginx] No supported package manager found\" >&2; exit 1\nfi\nsystemctl enable nginx && systemctl start nginx\necho \"[nginx] Done\"\n','root','bash');
INSERT INTO `configurations` (`id`, `name`, `platform`, `category`, `depends_on`, `script`, `run_as`, `type`) VALUES (12,'postfix','linux','service','[{\"name\":\"install-package\",\"vars\":{\"PACKAGE\":\"postfix\"}},{\"name\":\"enable-service\",\"vars\":{\"SERVICE\":\"postfix\"}}]','#!/bin/bash\necho \"[postfix] Installed via install-package, enabled via enable-service\"\n','root','bash');
INSERT INTO `configurations` (`id`, `name`, `platform`, `category`, `depends_on`, `script`, `run_as`, `type`) VALUES (13,'roundcube','linux','service',NULL,'#!/bin/bash\nset -e\nif command -v apt-get > /dev/null; then\n    DEBIAN_FRONTEND=noninteractive apt-get install -y \\\n        apache2 mariadb-server php php-mysql php-xml php-mbstring php-intl \\\n        php-net-smtp php-net-socket roundcube roundcube-mysql roundcube-plugins\n    a2enconf roundcube 2>/dev/null || true\n    systemctl enable apache2  && systemctl restart apache2\n    systemctl enable mariadb  && systemctl start  mariadb\nelif command -v dnf > /dev/null; then\n    dnf install -y epel-release\n    dnf install -y httpd mariadb-server php php-mysqlnd php-xml php-mbstring roundcubemail\n    systemctl enable httpd   && systemctl start httpd\n    systemctl enable mariadb && systemctl start mariadb\nelif command -v yum > /dev/null; then\n    yum install -y epel-release\n    yum install -y httpd mariadb-server php php-mysql php-xml php-mbstring roundcubemail\n    systemctl enable httpd   && systemctl start httpd\n    systemctl enable mariadb && systemctl start mariadb\nelse\n    echo \"[roundcube] No supported package manager found\" >&2; exit 1\nfi\necho \"[roundcube] Done\"\n','root','bash');
INSERT INTO `configurations` (`id`, `name`, `platform`, `category`, `depends_on`, `script`, `run_as`, `type`) VALUES (14,'splunk','linux','service','[{\"name\": \"create-user\", \"vars\": {\"USERNAME\": \"splunk\"}}]','#!/bin/bash\nset -e\nSPLUNK=\"/opt/splunk/bin/splunk\"\n\nif [ -f \"$SPLUNK\" ]; then\n    echo \"[splunk] Already installed — starting service\"\n    $SPLUNK start --accept-license --answer-yes --no-prompt || true\n    exit 0\nfi\n\nif command -v apt-get > /dev/null; then\n    DEBIAN_FRONTEND=noninteractive apt-get install -y wget\n    wget -q -O /tmp/splunk.deb \"https://download.splunk.com/products/splunk/releases/10.4.0/linux/splunk-10.4.0-f798d4d49089-linux-amd64.deb\"\n    dpkg -i /tmp/splunk.deb\nelif command -v dnf > /dev/null; then\n    dnf install -y wget\n    wget -q -O /tmp/splunk.rpm \"https://download.splunk.com/products/splunk/releases/10.4.0/linux/splunk-10.4.0-f798d4d49089.x86_64.rpm\"\n    rpm -ivh /tmp/splunk.rpm\nelif command -v yum > /dev/null; then\n    yum install -y wget\n    wget -q -O /tmp/splunk.rpm \"https://download.splunk.com/products/splunk/releases/10.4.0/linux/splunk-10.4.0-f798d4d49089.x86_64.rpm\"\n    rpm -ivh /tmp/splunk.rpm\nelse\n    echo \"[splunk] No supported package manager found\" >&2; exit 1\nfi\n\n# First-time setup: set admin password and accept license\n$SPLUNK start --accept-license --answer-yes --no-prompt \\\n    --seed-passwd \"changeme123!\"\n$SPLUNK enable boot-start -systemd-managed 1 || $SPLUNK enable boot-start\necho \"[splunk] Done\"\n','root','bash');
INSERT INTO `configurations` (`id`, `name`, `platform`, `category`, `depends_on`, `script`, `run_as`, `type`) VALUES (15,'vsftpd','linux','service','[{\"name\":\"install-package\",\"vars\":{\"PACKAGE\":\"vsftpd\"}},{\"name\":\"enable-service\",\"vars\":{\"SERVICE\":\"vsftpd\"}}]','#!/bin/bash\necho \"[vsftpd] Installed via install-package, enabled via enable-service\"\n','root','bash');
INSERT INTO `configurations` (`id`, `name`, `platform`, `category`, `depends_on`, `script`, `run_as`, `type`) VALUES (16,'create-user','linux','misconfiguration',NULL,'#!/bin/bash\nset -e\nid -u \"$USERNAME\" &>/dev/null || useradd -m \"$USERNAME\"\necho \"[create-user] $USERNAME ready\"\n','root','bash');
INSERT INTO `configurations` (`id`, `name`, `platform`, `category`, `depends_on`, `script`, `run_as`, `type`) VALUES (20,'install-package','linux','misconfiguration',NULL,'#!/bin/bash\nset -e\nif command -v apt-get > /dev/null; then\n    DEBIAN_FRONTEND=noninteractive apt-get install -y \"$PACKAGE\"\nelif command -v dnf > /dev/null; then\n    dnf install -y \"$PACKAGE\"\nelif command -v yum > /dev/null; then\n    yum install -y \"$PACKAGE\"\nelif command -v apk > /dev/null; then\n    apk add --no-cache \"$PACKAGE\"\nelse\n    echo \"[install-package] No supported package manager found\" >&2; exit 1\nfi\necho \"[install-package] Installed $PACKAGE\"\n','root','bash');
INSERT INTO `configurations` (`id`, `name`, `platform`, `category`, `depends_on`, `script`, `run_as`, `type`) VALUES (21,'enable-service','linux','misconfiguration',NULL,'#!/bin/bash\nset -e\nif command -v systemctl > /dev/null; then\n    systemctl enable \"$SERVICE\"\n    systemctl start \"$SERVICE\"\nelif command -v rc-update > /dev/null; then\n    rc-update add \"$SERVICE\" default\n    rc-service \"$SERVICE\" start\nelse\n    echo \"[enable-service] No supported service/init manager found\" >&2; exit 1\nfi\necho \"[enable-service] Enabled and started $SERVICE\"\n','root','bash');
INSERT INTO `configurations` (`id`, `name`, `platform`, `category`, `depends_on`, `script`, `run_as`, `type`) VALUES (23,'example-evil-image','linux','vulnerability','[]','# if you were evil, you could do imix instead\necho \"hi\"\ncp ./evil-img.png /tmp','root','bash');
INSERT INTO `configurations` (`id`, `name`, `platform`, `category`, `depends_on`, `script`, `run_as`, `type`) VALUES (24,'disable-system-firewall','windows','misconfiguration','[]','Set-NetFirewallProfile -Enabled False','Administrator','powershell');
INSERT INTO `configurations` (`id`, `name`, `platform`, `category`, `depends_on`, `script`, `run_as`, `type`) VALUES (25,'ssh','linux','service','[]','#!/bin/bash\nset -e\n\nif command -v apt-get > /dev/null; then\n    DEBIAN_FRONTEND=noninteractive apt-get install -y openssh-server\n    systemctl enable --now ssh\nelif command -v dnf > /dev/null; then\n    dnf install -y openssh-server\n    systemctl enable --now sshd\nelif command -v yum > /dev/null; then\n    yum install -y openssh-server\n    systemctl enable --now sshd\nelif command -v apk > /dev/null; then\n    apk add --no-cache openssh\n    rc-update add sshd default\n    rc-service sshd start\nelse\n    echo \"No supported package manager found\" >&2\n    exit 1\nfi','root','bash');
INSERT INTO `configurations` (`id`, `name`, `platform`, `category`, `depends_on`, `script`, `run_as`, `type`) VALUES (26,'ssh-empty-passwords','linux','misconfiguration','[\"ssh\"]','sed -i \'1s/^/PermitEmptyPassword yes\\n/\' /etc/ssh/sshd_config\nif command -v dnf &> /dev/null; then\n	systemctl restart sshd\nelse\n	systemctl restart ssh\nfi','root','bash');
INSERT INTO `configurations` (`id`, `name`, `platform`, `category`, `depends_on`, `script`, `run_as`, `type`) VALUES (27,'unauthorized-ftp-server','linux','misconfiguration','[]','apt install -y vsftpd\nsystemctl enable vsftpd\nsystemctl start vsftpd','root','bash');
INSERT INTO `configurations` (`id`, `name`, `platform`, `category`, `depends_on`, `script`, `run_as`, `type`) VALUES (28,'www-data-shell','linux','misconfiguration','[]','sed -i \'/^www-data:/s|:[^:]*$|:/bin/bash|\' /etc/passwd','root','bash');
INSERT INTO `configurations` (`id`, `name`, `platform`, `category`, `depends_on`, `script`, `run_as`, `type`) VALUES (29,'bad-perms-userConfig','linux','misconfiguration','[]','chmod 666 /etc/passwd\nchmod 666 /etc/shadow\nchmod 666 /etc/crontab','root','bash');
/*!40000 ALTER TABLE `configurations` ENABLE KEYS */;
UNLOCK TABLES;
COMMIT;
SET AUTOCOMMIT=@OLD_AUTOCOMMIT;

SET @OLD_AUTOCOMMIT=@@AUTOCOMMIT, @@AUTOCOMMIT=0;
LOCK TABLES `attachments` WRITE;
/*!40000 ALTER TABLE `attachments` DISABLE KEYS */;
INSERT INTO `attachments` (`id`, `configuration_id`, `object_key`, `original_name`, `mime_type`, `size_bytes`, `uploaded_at`) VALUES (3,23,'23/062e57f3-5e61-4a07-acf5-1683647b5c77-Screenshot 2026-06-21 at 1.22.06â¯AM.png','evil-img.png','image/png',303111,'2026-06-25 05:56:56');
/*!40000 ALTER TABLE `attachments` ENABLE KEYS */;
UNLOCK TABLES;
COMMIT;
SET AUTOCOMMIT=@OLD_AUTOCOMMIT;
/*!40103 SET TIME_ZONE=@OLD_TIME_ZONE */;

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
/*M!100616 SET NOTE_VERBOSITY=@OLD_NOTE_VERBOSITY */;

